### ISSUE TITLE
Implement InitialPledgeForWeight calculation

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/actors#468]
Currently builtin/power/policy.go's `InitialPledgeForWeight` is a stub.

The calculation should be `20*BR(t)`, for now, where `BR(t)` is the share of block reward that the sector would earn in one day.

The implementation has parameters for circulating supply and total committed pledge, but does not use them for now. Leave these here to keep the plumbing in place for the quite-possible case that they will be part of the computation.

Consider #420 and #489 first.

**Comment by anorth** [comment]
We have assurance that the pledge will be a linear function of weight, so for batched commitments we should be able to compute `pledge(power1 + power2)` as equal to `pledge(power1) + pledge(power2)`.

See also #495.
